# Project configuration for DSPEditor

[project]
name = "DSPEditor"
version = "0.1.0"
description = "A C++ project created with cforge"
cpp_standard = "17"
binary_type = "executable"  # executable, shared_lib, static_lib, or header_only
authors = ["Your Name <your.email@example.com>"]
homepage = "https://github.com/yourusername/DSPEditor"
repository = "https://github.com/yourusername/DSPEditor.git"
license = "MIT"

[build]
build_type = "Debug"  # Debug, Release, RelWithDebInfo, MinSizeRel
directory = "build"
source_dirs = ["src"]
include_dirs = ["include", "deps/highfive/include", "deps/cli/include"]
# Uncomment to specify custom source patterns
# source_patterns = ["src/*.cpp", "src/**/*.cpp"]
# Uncomment to specify individual source files
# source_files = ["src/main.cpp", "src/example.cpp"]

[build.config.debug]
defines = ["DEBUG=1", "ENABLE_LOGGING=1"]
flags = ["-g", "-O0"]
cmake_args = ["-DENABLE_TESTS=ON"]

[build.config.release]
defines = ["NDEBUG=1"]
flags = ["-O3"]
cmake_args = ["-DENABLE_TESTS=OFF"]

[build.config.relwithdebinfo]
defines = ["NDEBUG=1"]
flags = ["-O2", "-g"]
cmake_args = []

[build.config.minsizerel]
defines = ["NDEBUG=1"]
flags = ["-Os"]
cmake_args = []

[test]
enabled = false
[package]
enabled = true
generators = []  # Package generators
# Windows generators: ZIP, NSIS
# Linux generators: TGZ, DEB, RPM
# macOS generators: TGZ
vendor = "Your Organization"
contact = "Your Name <your.email@example.com>"

# Dependencies section
# [dependencies]

# vcpkg dependencies
# [dependencies.vcpkg]
# fmt = "9.1.0"  # Package name = version
# curl = { version = "7.80.0", components = ["ssl"] }  # With components

# git dependencies
# [dependencies.git]
# json = { url = "https://github.com/nlohmann/json.git", tag = "v3.11.2" }
# spdlog = { url = "https://github.com/gabime/spdlog.git", branch = "v1.x" }

# system dependencies
# [dependencies.system]
# OpenGL = true  # System-provided dependency

# git dependencies
[dependencies.git]
highfive = { url = "https://github.com/highfive-devs/highfive.git", tag = "main" }
cli = { url = "https://github.com/daniele77/cli.git", tag = "master" }
